### YamlMime:QSharpType
uid: microsoft.quantum.canon.decomposeintotimestepsca
name: DecomposeIntoTimeStepsCA
type: function
namespace: Microsoft.Quantum.Canon
summary: >2
   Returns an operation implementing the Trotter–Suzuki integrator for
   a given operation.
syntax: "function DecomposeIntoTimeStepsCA (nSteps : Int, op : ((Int, Double, 'T) => () : Adjoint, Controlled), trotterOrder : Int) : ((Double, 'T) => () : Adjoint, Controlled)"
input:
  content: "(nSteps : Int, op : ((Int, Double, 'T) => () : Adjoint, Controlled), trotterOrder : Int)"
  types:
  - name: nSteps
    uid: microsoft.quantum.primitive.integer
  - name: op
    types:
    - types:
      - uid: microsoft.quantum.primitive.integer
      - uid: microsoft.quantum.primitive.float
      - uid: "'t"
    - uid: microsoft.quantum.primitive.void
  - name: trotterOrder
    uid: microsoft.quantum.primitive.integer
output:
  content: "((Double, 'T) => () : Adjoint, Controlled)"
  types:
  - summary: >2-
       Returns a unitary implementing the Trotter–Suzuki integrator, where
       the first parameter `Double` is the integration step size, and the
       second parameter is the target acted upon.
    types:
    - types:
      - uid: microsoft.quantum.primitive.float
      - uid: "'t"
    - uid: microsoft.quantum.primitive.void
