### YamlMime:QSharpNamespace
uid: microsoft.quantum.extensions.environment
name: Microsoft.Quantum.Extensions.Environment
operations:
- uid: microsoft.quantum.extensions.environment.getqubitsavailabletoborrow
  summary: |-
    Returns the number of qubits currently available to borrow.
    This includes unused qubits; that is, this includes the qubits
    returned by `GetQubitsAvailableToUse`.
- uid: microsoft.quantum.extensions.environment.getqubitsavailabletouse
  summary: Returns the number of qubits currently available to use.
...
